Suppress line length warning
oasis-roles/passwd pull request #3
Opened 2019-02-05 16:46 UTC by greg-hellings

Line length warnings from Ansible-lint duplicate those in yamllint, and
we are disabling it there for this particular line. Therefore, don't
have ansible-lint double check the line length for us

2019-02-06 17:44 UTC, robled requested changes

2019-02-06 17:44 UTC, robled commented on molecule/docker/molecule.yml
> +        - "204"
Since this option is not descriptive by itself, it might be worth adding a comment so nobody has to go look up what '204' means.

2019-02-06 17:44 UTC, robled commented on molecule/openstack/molecule.yml
> +        - "204"
Since this option is not descriptive by itself, it might be worth adding a comment so nobody has to go look up what '204' means.

2019-02-06 18:44 UTC, tehsmyers approved these changes
I generally agree with @robled's comments, but I think having to comment options like this in multiple files is annoying. I don't have a better idea, though.

2019-02-06 18:56 UTC, robled commented
> I generally agree with @robled's comments, but I think having to comment options like this in multiple files is annoying. I don't have a better idea, though.

Updating the meta_skeleton template with comments will help a bit, at least.

2019-02-08 15:32 UTC, greg-hellings commented
Added comments to the molecule.yml files

2019-02-08 16:03 UTC, robled approved these changes

2019-02-08 16:04 UTC, merged